name: CI
on: [push]
jobs:
    ci:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                step: ['lint', 'build', 'test:unit', 'test:e2e']
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - name: Prepare
              run: yarn install --frozen-lockfile

            - name: ${{matrix.step}}
              run: yarn ${{matrix.step}}